### ISSUE TITLE
not being able to define several attributes by commas 

### ISSUE THREAD

**Issue by vahdat-ab** [umple/umple#924] opened 2016-11-28 20:59 UTC
Currently, Umple doesn't allow defining more than one attribute with the same type using commas. For example, Umple cannot detect that there are two attributes in the following snippet. It considers it as an extra code.
```
class A{
  B b1,b2;
}
class B{}
```

**Comment by TimLethbridge** [comment] 2016-11-28 22:59
This is a duplicate of issue #254, which has been around for a very, very long time! So I will close

**Closed as completed by TimLethbridge** 2016-11-28 22:59 UTC
Labels: enhancement, Priority-Medium, Diffic-Easy, attributes
