### ISSUE TITLE
A warning message after clicking on "Start Over" button in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1822] opened 2021-08-05 17:07 UTC
## Summary

Within the UmpleOnline, the users can erase everything they have written/selected in the text editor or diagram pane by clicking on the "Start Over" button. Once clicked, there is not way to undo this action and get the work back. The message displayed in "Hover" action also does not say that details. A warning pop up message once clicked at this button can help users to reconfirm and avoid any accidental erase. 

## Steps to Reproduce

1. Go to the "TOOLS", then select the "Class Diagram" from the dropdown. Select an example "2DShapes".
![image](https://user-images.githubusercontent.com/82404135/128391149-d7b12357-7095-482c-b73d-ee5f8f3db228.png)
2. At the text editor, write "**Datetime createdOn**" at line number 11.
![image](https://user-images.githubusercontent.com/82404135/128391453-41cda33a-9caa-4ead-8427-efa7f2dba01f.png)
3. Go to the "SAVE & LOAD", and click "Start Over". 
![image](https://user-images.githubusercontent.com/82404135/128391598-39c1df7c-2b40-4512-b362-7697160d4326.png)
4. Now you will see the codes and changes are gone.

## Expected Feature

The system should give a warning pop up message showing "Are you sure you want to erase everything? Once erased, you'll not be able to retrieve your works"

**Comment by TimLethbridge** [comment] 2021-08-05 18:19
This is a duplicate of #1749 So I am closing it

**Closed as completed by TimLethbridge** 2021-08-05 18:19 UTC
