### ISSUE TITLE
USE Model generating invalid results when show in tabs is checked in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1720] opened 2021-05-27 21:27 UTC
## Summary

Within the UmpleOnline, the users can generate code (e.g. Java, C++, USE model, etc) based on the modeling language. In a sample scenario, a user can create a model and generate the source code accordingly. Based on the viewing preference, the user can check the "Show Files in Separate Tabs" or not. If the user checks that box, then the entire source is encapsulated in separate tabs where each tab contains its own code.

If a user generates the source code for "USE Model" and tries to see the result in separate tabs, the source code section vanishes. It does not show anything.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "USE Model".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119899026-98de0080-bf10-11eb-9448-a6c96c8b292e.png)
3. Scroll a bit down and check the box with the text "Show Files in Separate Tabs".
![image](https://user-images.githubusercontent.com/82404135/119898134-6aabf100-bf0f-11eb-8e57-c040563cda5a.png)

As soon as the user clicks the checkbox, the source code disappears. It shows no tab either.

## Expected Feature

When the checkbox is checked, the source is expected to be separated into multiple tabs according to the encapsulation logic.

**Comment by TimLethbridge** [comment] 2021-05-28 11:17
This is a duplicate of #1719 I am closing this one. All generators should be looked at for this same issue and the show in separate tabs removed when not generating source text.

**Closed as completed by TimLethbridge** 2021-05-28 11:17 UTC
