### ISSUE TITLE
Mixin does not include all inherited traits

### ISSUE THREAD

**Issue by ahmedvc** [umple/umple#1034] opened 2017-04-04 04:57 UTC
We can use multiple traits with a class. However, when using the mixin feature to define a trait, only the last mixin class will detect the trait. Considering the model below, only the trait Mix3 will be recognised.

trait Mix1{
  void test1(){
  }
}

trait Mix2{
  void test2(){
  }
}

trait Mix3{
  void test3(){
  }
}

class Test{
  isA Mix1;
}

class Test{
  isA Mix2;
}

class Test{
  isA Mix3;
}

The only way to get it working is to declare all of our traits in a single isA call as bellow

class Test{
  isA Mix1, Mix2, Mix3;
}

**Comment by vahdat-ab** [comment] 2017-04-04 13:52
I assigned this to me. 
It's odd because it must be done automatically by the Umple compiler. I'll explore it.

**Comment by vahdat-ab** [comment] 2017-05-13 07:20
This issue is not related to the way traits have been implemented. The source of the issue is the way mixins have been implemented. Consider the following example:
```
class C{
}

interface I{
}


class Test{
isA C;

}

class Test{
isA I;
}
```
The generator will disregard extending class `C` and just implement interface `I`

**Comment by opeyemiAdesina** [comment] 2017-05-13 19:49
@vahdat_ab, The model doesn't seem to correct Umple model... Two Umple classes with name: Test in the same model.

**Comment by vahdat-ab** [comment] 2017-05-13 21:24
@opeyemiAdesina I didn't get the point. Could you plz explain more?

**Comment by opeyemiAdesina** [comment] 2017-05-14 01:12
What I meant is that two classes has the same name in the model example you posted.

**Comment by vahdat-ab** [comment] 2017-05-14 01:15
@opeyemiAdesina yes. It is a valid example. In Umple, we call it mixins. It allows us to separate a class, for example, to modeling and language specific parts.
we used it a lot inside Umple compiler.

**Comment by TimLethbridge** [comment] 2017-05-14 01:50
Two classes with the same name just mix. That is the whole point

Timothy C Lethbridge

**Closed as completed** 2017-05-14 02:09 UTC
Labels: Traits
