### ISSUE TITLE
Wrong generated code for association member variables list if the class is named "A" when in "show files in different tabs" mode

### ISSUE THREAD

**Issue by amidzak** [umple/umple#971] opened 2017-01-23 23:36 UTC
Consider the following Umple code
`
class A{
}
class C{
      * -- * A;
}
`

This generates the following code for the Type of the list in the generated code:
`
  //------------------------
  // MEMBER VARIABLES
  //------------------------
 
  //C Associations
  private List\<a> as;
 
  //------------------------
  // CONSTRUCTOR
  //------------------------
 
  public C()
  {
        as = new ArrayList\</a>\<a>();
  }
 
  //------------------------
  // INTERFACE
  //------------------------
 
  public A getA(int index)
  {
        A aA = as.get(index);
        return aA;
  }
 
  public List\</a>\<a> getAs()
  {
        List\</a>\<a> newAs = Collections.unmodifiableList(as);
        return newAs;
  }
`

**Comment by Nava2** [comment] 2017-01-24 00:32
This is a duplicate of #970, I think. 

Also, when you paste multiline code fragments, use three ` symbols.

**Comment by TimLethbridge** [comment] 2017-11-21 16:37
This was resolved some time ago

**Closed as completed by TimLethbridge** 2017-11-21 16:37 UTC
