### ISSUE TITLE
Reaching final state does not stop state machine

### ISSUE THREAD

**Issue by mheng86** [umple/umple#1322] opened 2018-07-06 15:02 UTC
## Specify a Brief Description

I write umple code for two state machines RoleX and RoleY. The generated Java code is fine, the problem is when both state machines reach the final state, the program does not stop. 

the following is the umple code:
```
//
class RoleX{
   1 -- 0..1 RoleY; 
   
   pooled sm_x{
    s1 {
     sendm1/{roleY.rcvm1();} ->s2;
    }
    s2 {
       sendm2/{roleY.rcvm2();}->s3;
     
    }
    s3 {
      rcvm3 -> s4;
    }
     
     final s4{}
    
  }
  trace sm_x;
 }


class RoleY{
  pooled sm_y {
    s1 {
      rcvm1 -> s2;
    }
    s2 {
      rcvm2 /{roleX.rcvm3();} -> s3;
    }
    final s3{}
   
  }
  trace sm_y;
  
 }
  
}
```

**Comment by TimLethbridge** [comment] 2018-07-06 18:20
The person who investigates this should explore the case of a single class with a state machine with a final state, and also concurrent regions with final states, to check if there are other cases.

**Comment by ZainabAlShowely** [comment] 2018-07-09 19:30
The issue arises for any pooled or queued state machine that reaches a final state, as the thread is not stopped and the state machine continues waiting for events. A single class also raises the same issue.

**Comment by mheng86** [comment] 2018-07-09 19:53
Is this normal?

**Comment by ZainabAlShowely** [comment] 2018-07-09 20:01
No, the expected behavior would be for the state machine to be terminated when it reaches a final state. I am currently working on a fix to resolve the issue.

**Comment by ZainabAlShowely** [comment] 2018-07-10 15:24
The issue is fixed when generating Java code, but it might occur in other languages, so testing for those that do implement state machines is needed next. Alternatively, new issues could be opened.

**Comment by TimLethbridge** [comment] 2018-07-10 15:42
In fact there is no other langauge that properly implements state machines, other than C++; Normally @ahmedvc follows up with any relevant changes and modifies the C++ appropriately. So I think this issue is ready to be closed.

**Comment by ZainabAlShowely** [comment] 2018-07-10 15:49
OK, I think it's ready to be closed as well in that case; I am closing the issue.

**Closed as completed by ZainabAlShowely** 2018-07-10 15:49 UTC
Labels: Component-SemanticsAndGen, Diffic-Med, stateMachines, Priority-VHigh
