### ISSUE TITLE
Generate SVG option not working for structure diagram in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple/umple#1724] opened 2021-05-28 03:55 UTC
## Summary

Within the UmpleOnline, the users can generate a structure diagram based on the modeling language. In a sample scenario, a user can create a model, select the "structure diagram" from the dropdown, clicks the generate button, and finally the system displays the diagram.

Once the user clicks on the "Generate SVG" button, the system starts loading the diagram. The loading icon continues for hours but does not return anything.

## Steps to Reproduce

1. Click the "Tools" menu item, select the example as "Class Diagrams >> Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/119898743-3ab11d80-bf10-11eb-8646-23683e8fd6aa.png)
2. Under the "Generate" section, select the target programming language as "Structure Diagram".  Click "Generate It".
![image](https://user-images.githubusercontent.com/82404135/119926725-e45ed180-bf45-11eb-8725-235dd1c9c2a1.png)
3. Scroll a bit down and click on the "Generate SVG" button.
![image](https://user-images.githubusercontent.com/82404135/119926815-153f0680-bf46-11eb-8f50-adc36abd4325.png)

The system goes into an infinite waiting time to return the result. After even a few hours of waiting, the system returns nothing. Moreover, the user cannot cancel that operation.  If the user tries to change the "example" or "generate" dropdown to cancel this operation, the system crashes.
![image](https://user-images.githubusercontent.com/82404135/119927081-b7f78500-bf46-11eb-9ae9-8989ec4ae7c0.png)

## Expected Feature

The system should generate the SVG once the button is clicked. If it fails to return the diagram, the system should return an appropriate message to the users.

**Comment by TimLethbridge** [comment] 2021-05-28 10:53
It is not clear what the 'Generate SVG' is supposed to do, since the diagram is being generated. It might be that there is an intent to download and SVG. This needs to be fixed, or the option removed. Please check with the team lead when the problem is understood, before taking action.

**Comment by TimLethbridge** [comment] 2021-05-28 10:55
I have marked this as priority high to at least get rid of the 'hang'. Then it can be dropped to priority low to actually 'do the right thing'.

**Closed as completed** 2021-08-15 16:00 UTC
Labels: Component-UmpleOnline, Priority-High, Diffic-Med, composite structure
